---
# tasks file for docker

- fail: msg='OS not suported'
  when: '"{{ ansible_os_family }}" not in container_specific_os_family or
         "{{ ansible_os_family }}" not in generic_linux_os_family'

# install docker-py
- include: install_general_linux_os_family.yml
  when: '"{{ ansible_os_family }}" in generic_linux_os_family'

- include: install_container_specific_os_family.yml
  when: '"{{ ansible_os_family }}" in container_specific_os_family'

