---

# 1/3 Copy TLS certificates to Docker host.
- name: create docker TLS directory
  file: path={{ docker_tls_path }} state=directory

- name: install docker TLS credentials
  template: src={{ item.from }} dest={{ item.to }} mode=0644
  with_items:
    - from: ca.pem.j2
      to: "{{ docker_tls_path }}/ca.pem"
    - from: key.pem.j2
      to: "{{ docker_tls_path }}/key.pem"
    - from: cert.pem.j2
      to: "{{ docker_tls_path }}/cert.pem"

# 2/3 Drop-in configuration, so docker host loads the certificates when the
# service is initialized.
- name: create docker Drop-in directory
  become: yes
  become_user: root
  file: path={{ docker_daemon_path }} state=directory

- name: copy template
  template:
    src=docker-daemon.conf.j2
    dest={{ docker_daemon_path }}/10-docker-tls.conf
    mode=0644

- debug: msg="trigger docker stop"
  notify:
  - stop docker service
  changed_when: true

# TODO: When upgrade to ansible >=2.2 version convert this task into a handle
- name: reload systemd
  become: yes
  become_user: root
  shell: systemctl daemon-reload

- debug: msg="trigger docker restart"
  notify:
  - restart docker service
  changed_when: true
