---

- name: reload systemd
  become: yes
  become_user: root
  systemd: daemon_reload=yes

- name: enable etcd service
  become: yes
  become_user: root
  service: name=etcd.service enabled=yes

- name: restart etcd service
  become: yes
  become_user: root
  service: name=etcd.service state=restarted

- name: enable docker service
  become: yes
  become_user: root
  service: name=docker.service enabled=yes

- name: restart docker service
  become: yes
  become_user: root
  service: name=docker.service state=restarted

- name: stop docker service
  become: yes
  become_user: root
  service: name=docker.service state=stopped
